client_config_backend: settings
client_config:
  client_id: 253062990338-0h4aja518ot9tcv4r17i6o1r40gkh6ch.apps.googleusercontent.com
  client_secret: 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
save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json
get_refresh_token: True
oauth_scope:
- https://www.googleapis.com/auth/drive.file